---
# write_device_name:
    hostname: # device IP/hostname
    platform: # platform type
    username: # username
    password: # password
# write_device_name:
    hostname: # device IP/hostname
    platform: # platform type
    username: # username
    password: # password
# write_device_name:
    hostname: # device IP/hostname
    platform: # platform type
    username: # username
    password: # password   

